// <auto-generated />
using System;
using MVCCRUD.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVCCRUD.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MVCCRUD.Entities.Concrete.Musteri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Musteriler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Ali",
                            Email = "ali.yilmaz@example.com",
                            Soyad = "Yılmaz"
                        },
                        new
                        {
                            Id = 2,
                            Ad = "Ayşe",
                            Email = "ayse.kara@example.com",
                            Soyad = "Kara"
                        },
                        new
                        {
                            Id = 3,
                            Ad = "Mehmet",
                            Email = "mehmet.demir@example.com",
                            Soyad = "Demir"
                        },
                        new
                        {
                            Id = 4,
                            Ad = "Fatma",
                            Email = "fatma.ozturk@example.com",
                            Soyad = "Öztürk"
                        },
                        new
                        {
                            Id = 5,
                            Ad = "Hasan",
                            Email = "hasan.celik@example.com",
                            Soyad = "Çelik"
                        },
                        new
                        {
                            Id = 6,
                            Ad = "Zeynep",
                            Email = "zeynep.koc@example.com",
                            Soyad = "Koç"
                        },
                        new
                        {
                            Id = 7,
                            Ad = "Emre",
                            Email = "emre.aydin@example.com",
                            Soyad = "Aydın"
                        },
                        new
                        {
                            Id = 8,
                            Ad = "Seda",
                            Email = "seda.akman@example.com",
                            Soyad = "Akman"
                        },
                        new
                        {
                            Id = 9,
                            Ad = "Burak",
                            Email = "burak.sonmez@example.com",
                            Soyad = "Sönmez"
                        },
                        new
                        {
                            Id = 10,
                            Ad = "Elif",
                            Email = "elif.yavuz@example.com",
                            Soyad = "Yavuz"
                        });
                });

            modelBuilder.Entity("MVCCRUD.Entities.Concrete.Siparis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MusteriId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SiparisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("UrunId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MusteriId");

                    b.HasIndex("UrunId");

                    b.ToTable("Siparisler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MusteriId = 1,
                            SiparisTarihi = new DateTime(2024, 10, 30, 15, 42, 10, 738, DateTimeKind.Local).AddTicks(5568),
                            UrunId = 1
                        },
                        new
                        {
                            Id = 2,
                            MusteriId = 1,
                            SiparisTarihi = new DateTime(2024, 10, 30, 15, 42, 10, 738, DateTimeKind.Local).AddTicks(5587),
                            UrunId = 2
                        },
                        new
                        {
                            Id = 3,
                            MusteriId = 2,
                            SiparisTarihi = new DateTime(2024, 10, 30, 15, 42, 10, 738, DateTimeKind.Local).AddTicks(5588),
                            UrunId = 3
                        },
                        new
                        {
                            Id = 4,
                            MusteriId = 2,
                            SiparisTarihi = new DateTime(2024, 10, 30, 15, 42, 10, 738, DateTimeKind.Local).AddTicks(5589),
                            UrunId = 4
                        },
                        new
                        {
                            Id = 5,
                            MusteriId = 3,
                            SiparisTarihi = new DateTime(2024, 10, 30, 15, 42, 10, 738, DateTimeKind.Local).AddTicks(5590),
                            UrunId = 5
                        },
                        new
                        {
                            Id = 6,
                            MusteriId = 3,
                            SiparisTarihi = new DateTime(2024, 10, 30, 15, 42, 10, 738, DateTimeKind.Local).AddTicks(5592),
                            UrunId = 6
                        },
                        new
                        {
                            Id = 7,
                            MusteriId = 4,
                            SiparisTarihi = new DateTime(2024, 10, 30, 15, 42, 10, 738, DateTimeKind.Local).AddTicks(5593),
                            UrunId = 7
                        },
                        new
                        {
                            Id = 8,
                            MusteriId = 5,
                            SiparisTarihi = new DateTime(2024, 10, 30, 15, 42, 10, 738, DateTimeKind.Local).AddTicks(5594),
                            UrunId = 8
                        },
                        new
                        {
                            Id = 9,
                            MusteriId = 6,
                            SiparisTarihi = new DateTime(2024, 10, 30, 15, 42, 10, 738, DateTimeKind.Local).AddTicks(5596),
                            UrunId = 9
                        },
                        new
                        {
                            Id = 10,
                            MusteriId = 7,
                            SiparisTarihi = new DateTime(2024, 10, 30, 15, 42, 10, 738, DateTimeKind.Local).AddTicks(5597),
                            UrunId = 10
                        },
                        new
                        {
                            Id = 11,
                            MusteriId = 8,
                            SiparisTarihi = new DateTime(2024, 10, 30, 15, 42, 10, 738, DateTimeKind.Local).AddTicks(5598),
                            UrunId = 1
                        },
                        new
                        {
                            Id = 12,
                            MusteriId = 9,
                            SiparisTarihi = new DateTime(2024, 10, 30, 15, 42, 10, 738, DateTimeKind.Local).AddTicks(5855),
                            UrunId = 2
                        },
                        new
                        {
                            Id = 13,
                            MusteriId = 10,
                            SiparisTarihi = new DateTime(2024, 10, 30, 15, 42, 10, 738, DateTimeKind.Local).AddTicks(5860),
                            UrunId = 3
                        },
                        new
                        {
                            Id = 14,
                            MusteriId = 4,
                            SiparisTarihi = new DateTime(2024, 10, 30, 15, 42, 10, 738, DateTimeKind.Local).AddTicks(5862),
                            UrunId = 5
                        },
                        new
                        {
                            Id = 15,
                            MusteriId = 5,
                            SiparisTarihi = new DateTime(2024, 10, 30, 15, 42, 10, 738, DateTimeKind.Local).AddTicks(5863),
                            UrunId = 6
                        },
                        new
                        {
                            Id = 16,
                            MusteriId = 6,
                            SiparisTarihi = new DateTime(2024, 10, 30, 15, 42, 10, 738, DateTimeKind.Local).AddTicks(5865),
                            UrunId = 7
                        },
                        new
                        {
                            Id = 17,
                            MusteriId = 7,
                            SiparisTarihi = new DateTime(2024, 10, 30, 15, 42, 10, 738, DateTimeKind.Local).AddTicks(5866),
                            UrunId = 8
                        },
                        new
                        {
                            Id = 18,
                            MusteriId = 8,
                            SiparisTarihi = new DateTime(2024, 10, 30, 15, 42, 10, 738, DateTimeKind.Local).AddTicks(5868),
                            UrunId = 9
                        },
                        new
                        {
                            Id = 19,
                            MusteriId = 9,
                            SiparisTarihi = new DateTime(2024, 10, 30, 15, 42, 10, 738, DateTimeKind.Local).AddTicks(5869),
                            UrunId = 10
                        },
                        new
                        {
                            Id = 20,
                            MusteriId = 10,
                            SiparisTarihi = new DateTime(2024, 10, 30, 15, 42, 10, 738, DateTimeKind.Local).AddTicks(5871),
                            UrunId = 1
                        });
                });

            modelBuilder.Entity("MVCCRUD.Entities.Concrete.Urun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Fiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UrunAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Urunler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Fiyat = 2500m,
                            UrunAdi = "Laptop"
                        },
                        new
                        {
                            Id = 2,
                            Fiyat = 1500m,
                            UrunAdi = "Akıllı Telefon"
                        },
                        new
                        {
                            Id = 3,
                            Fiyat = 1200m,
                            UrunAdi = "Tablet"
                        },
                        new
                        {
                            Id = 4,
                            Fiyat = 300m,
                            UrunAdi = "Kulaklık"
                        },
                        new
                        {
                            Id = 5,
                            Fiyat = 2000m,
                            UrunAdi = "Masaüstü Bilgisayar"
                        },
                        new
                        {
                            Id = 6,
                            Fiyat = 800m,
                            UrunAdi = "Monitör"
                        },
                        new
                        {
                            Id = 7,
                            Fiyat = 400m,
                            UrunAdi = "Klavyeli"
                        },
                        new
                        {
                            Id = 8,
                            Fiyat = 600m,
                            UrunAdi = "Yazıcı"
                        },
                        new
                        {
                            Id = 9,
                            Fiyat = 250m,
                            UrunAdi = "Modem"
                        },
                        new
                        {
                            Id = 10,
                            Fiyat = 500m,
                            UrunAdi = "Harici Disk"
                        });
                });

            modelBuilder.Entity("MVCCRUD.Entities.Concrete.Siparis", b =>
                {
                    b.HasOne("MVCCRUD.Entities.Concrete.Musteri", "Musteri")
                        .WithMany("Siparisler")
                        .HasForeignKey("MusteriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MVCCRUD.Entities.Concrete.Urun", "Urun")
                        .WithMany("Siparisler")
                        .HasForeignKey("UrunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Musteri");

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("MVCCRUD.Entities.Concrete.Musteri", b =>
                {
                    b.Navigation("Siparisler");
                });

            modelBuilder.Entity("MVCCRUD.Entities.Concrete.Urun", b =>
                {
                    b.Navigation("Siparisler");
                });
#pragma warning restore 612, 618
        }
    }
}
